document.write("<OPTION selected>[m3]") ;
document.write("<OPTION>[km3]") ;
document.write("<OPTION>[dm3 = l]") ;
document.write("<OPTION>[cm3 = ml]") ;
document.write("<OPTION>[mm3]") ;
document.write("<OPTION>[cal3],( [in3] )") ;
document.write("<OPTION>[stopa3],( [ft3] )") ;
document.write("<OPTION>[jard3],( [yard3] )") ;
document.write("<OPTION>[galon USA],( [gal] )") ;
document.write("<OPTION>[galon ang],( [galUK] )") ;
document.write("<OPTION>[galon suchy??],( [galD] )") ;
document.write("<OPTION>[buszel USA],( [bu] )") ;
document.write("<OPTION>[buszel ang],( [buUK] )") ;
document.write("<OPTION>[baryłka USA wino],( [bbl?] )") ;
document.write("<OPTION>[baryłka ang],( [bblUK] )") ;
document.write("<OPTION>[baryłka petro],( [bo] )") ;
